### ISSUE TITLE
[OTHER] <Need help applying>

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Pradumnasaraf/SocialSlash#13]
### What would you like to share?

 I tried this but upon creating my profile, I ended up on your gihub profile

**Comment by Pradumnasaraf** [comment]
Can you explain a little bit more about what you tried and what went wrong?

**Comment by Pradumnasaraf** [comment]
Oh yes, docs are wrong

Thank you so much for reporting. We don't need to fork the repo, vercel will clone it for you. Also, we need to update the links in the clone one. Sorry for inconvenience

Can you please delete all the forks and clone (if there are) and try again from start and let me know if works or not? I have updated the docs https://github.com/Pradumnasaraf/SocialSlash/blob/main/README.md

<img width="929" alt="Screenshot 2023-02-11 at 3 54 29 PM" src="https://user-images.githubusercontent.com/51878265/218252973-6ba1fd74-bad8-4690-a17e-6ea50c5c3c40.png">

**Comment by Soumya-Kushwaha** [comment]
Hello!

If I don't fork the repo already, where do I install Vercel, provided I do not want to install it on all repos. It's asking fto select "atleast 1 repo"?

**Comment by Pradumnasaraf** [comment]
> Hello!
> 
> If I don't fork the repo already, where do I install Vercel, provided I do not want to install it on all repos. It's asking fto select "atleast 1 repo"?

Didn't get you. You need to click the button and it will open a window that will create a new clone, not the fork. You can name it, it will not install on all your repos

**Comment by Soumya-Kushwaha** [comment]
What repo do I select here?
![image](https://user-images.githubusercontent.com/87495134/218297614-2be2a699-1c4f-42f4-a59b-ad97fdb1313b.png)

**Comment by Pradumnasaraf** [comment]
Is this 1st time you are using Vercel? Because this option comes when you setup it up for the 1st time.

**Comment by Soumya-Kushwaha** [comment]
Yes, first time!

**Comment by Pradumnasaraf** [comment]
Ah, got it. You can give the **All Repo..** permission, it will only read your repo info. Will help in the future as well.

If not, you need to go in the fork way. Fork then go on vercel and deploy (don't use the button then)

**Comment by Pradumnasaraf** [comment]
Closing this. If you still face any issues feel free to open a new one. Thank you for sharing your feedback
