### ISSUE TITLE
[BUG] fix `prettier.yml` workflow version number

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/SocialSlash#18]
### Description

Fix the version of 2 actions

```diff
- uses: actions/checkout@v2
+ uses: actions/checkout@v3
```

```diff
- uses: actions/setup-node@v2
+ uses: actions/setup-node@v3
```

File path - https://github.com/Pradumnasaraf/SocialSlash/blob/main/.github/workflows/prettier.yml

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue

**Comment by kalyan-vurugonda** [comment]
Hey @Pradumnasaraf, I would like to contribute to this.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf, I would like to contribute to this.

go ahead
