### ISSUE TITLE
[BUG] Add a name to greetings workflow

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/SocialSlash#19]
### Description

Just above the `on:` property, add a `name:` property.

I should look like this

```yaml
name: Greetings

on:
```

File path - https://github.com/Pradumnasaraf/SocailSlash/blob/main/.github/workflows/greetings.ymlthe 

### Screenshots
https://github.com/Pradumnasaraf/SocialSlash/blob/24eda6954c133ce8fc5378e9ef287f3dc83876fa/.github/workflows/greetings.yml#L1

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue

**Comment by yeshwantthota** [comment]
can you assign this to me please, I would like to work on this issue?

**Comment by Coderamrin** [comment]
is the issue available?
if so, assign it to me.

**Comment by Pradumnasaraf** [comment]
> is the issue available? if so, assign it to me.

Yes, go ahead

**Comment by Shipkush7** [comment]
is the issue available??? if so....can i work on that?

**Comment by Abhishek-00** [comment]
Yes you can work on it @Shipkush

**Comment by Pradumnasaraf** [comment]
This issue is already fixed look for a different issue.

Close #26
