### ISSUE TITLE
[DOCS] Improve README

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/SocialSlash#2]
### Description

- Change the name in README to `Social Slash` and center it
- Add all the tech stack used, Node, Express.

**Comment by aroramrinaal** [comment]
@Pradumnasaraf, I can work on this issue.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf, I can work on this issue.

Thank you for your interest. Yes, go ahead!!

**Comment by KendallDoesCoding** [comment]
Any update on this?

**Comment by hasnainmakada-99** [comment]
Hey, @Pradumnasaraf is this issue still open?

**Comment by Pradumnasaraf** [comment]
> Hey, @Pradumnasaraf is this issue still open?

Yes, it's open. You can work on it if you want.

**Comment by hasnainmakada-99** [comment]
Sure @Pradumnasaraf
