### ISSUE TITLE
[BUG] <description>

### ISSUE THREAD

**Issue by hrshtmlng** [Pradumnasaraf/SocialSlash#28]
### Description

The site isn't working

### Screenshots

![Screenshot (173)](https://user-images.githubusercontent.com/101478591/219800639-36a9d6d3-42b8-416f-9354-3063f52cdd5c.png)

**Comment by Pradumnasaraf** [comment]
Hey,
It's not a website. It's an API. So we don't have a homepage. You can see the message on the website that the **API working fine**.

Closing this issue
