### ISSUE TITLE
[FEATURE] Add Husky - Git Hook support

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/SocialSlash#5]
### Description

[docs](https://typicode.github.io/husky/#/)

### Screenshots

![Screenshot 2022-07-10 at 4 34 50 PM](https://user-images.githubusercontent.com/51878265/178142257-bb955d46-99cb-46fb-bf79-8098dbc3b5db.png)

**Comment by hasnainmakada-99** [comment]
Hey @Pradumnasaraf, can you please be more specific about this issue and explain to me what husky do, Because I am interested in working on this issue

**Comment by VivekAlhat** [comment]
Hi @Pradumnasaraf, if this issue is still open for PR. Can I work on it?

**Comment by Pradumnasaraf** [comment]
Hey, for now, we are not planning to add this. Sorry, I forgot to close it.
